#!/usr/bin/python
from __future__ import print_function  #allows print as function
import sys
import csv # see https://docs.python.org/2/library/csv.html

#download the responses to this file
FN = 'q4.csv'
GRADE_FILE_HEADER = """*/,
* this file generated by quiz marking python script
q4 / 8
"""


answer = [
    "Lawyers",
    "1890",
    "Snoopy journalism on the occasion of his daughter's wedding",
    "A letter in the Harvard Law Review",
    "A Law professor",
    "1960",
    "An article for the California Law Review in which he examined the implications of many cases concerned with privacy",
    "Acceptance under common law of the idea that violating a person's privacy is a wrong",
]

# be paranoid about data until sure it's clean (missing students)
SCRUB = True

PRINT_STATS = True

# just give mark of 1 or zero
PASS_OR_FAIL = False #True

# make this into python module
execfile("mark-quiz.py")
