#!/usr/bin/python
from __future__ import print_function  #allows print as function
import sys
import csv # see https://docs.python.org/2/library/csv.html

#download the responses to this file
# INFORMATION
FN = 'qi.csv'
GRADE_FILE_HEADER = """*/,
* this file generated by quiz marking python script
qi / 5
"""

#"No one should be allowed to build a building with proprietary knowledge because that restricts our ability 
#to fix the buildings 
#infrastructure if it were to break. 
#Software is just as important and is likewise susceptible to weaknesses.",

# 
# ouch, had to hack out , in correct answer by hand.
# weird google form empty field between 4 and 5
answer = [
    "No one published results so no one got a reality check",
    "A computer (hardware) that can run all but one program is not a computer (and also impossible to build).",
    "Prosthetic legs that walk you in a direction you do not wish to go.",
    "Giving the public the decryption key hidden inside the reading device",
    "cut off peoples access to the internet as punishment for 3 accusations of copyright infringement",
]


# be paranoid about data until sure it's clean
SCRUB = False

#print question stats
PRINT_STATS = True

# just give mark of 1 or zero
PASS_OR_FAIL = False

#VERBOSE = True

# make this into python module
execfile("mark-quiz.py")
