#!/usr/bin/python
from __future__ import print_function  #allows print as function
import sys
import csv # see https://docs.python.org/2/library/csv.html

#download the responses to this file
#EQUITY
FN = 'qe.csv'
GRADE_FILE_HEADER = """*/,
* this file generated by quiz marking python script
qe / 8
"""


# ouch, had to hack out , in correct answer by hand.
answer = [
"increases until 1980 then decreases",
"the targeted marketing of the personal computer",
"Carnegie Mellon and Harvey Mudd",
"The Difference Principle",
"Mike",
"none of the above",
"individuals perform worse on tests when they are reminded of their status as an individual in an identifiable protected class prior to taking the test",
"A & C"
]

# be paranoid about data until sure it's clean
SCRUB = False

#print question stats
PRINT_STATS = True

# just give mark of 1 or zero
PASS_OR_FAIL = False

#VERBOSE = True

# make this into python module
execfile("mark-quiz.py")

