#!/usr/bin/python

from __future__ import print_function  #allows print as function
import sys
import csv # see https://docs.python.org/2/library/csv.html

#download the responses to this file
FN = 'q1.csv'

GRADE_FILE_HEADER = """*/,
* this file generated by quiz marking python script
q1 / 7
"""

answer = [
 "MIT",
 "In car GPS based navigation system",
 "Being Digital",
 "Connecting the last billion people to the Internet",
 "Innovation will be done by informal groups of engineers scientists and gifted amateurs.",
 "Engineers and scientists will do it themselves as they go along.",
# "SKIP_ME" # 26% got it wrong?
 "When folks share data about themselves at the same time as follow data shared by their associates"
]

# be paranoid about data until sure it's clean
SCRUB = False

# just give mark of 1 or zero
PASS_OR_FAIL = False

PRINT_STATS = True

# make this into python module
execfile("mark-quiz.py")
