#!/usr/bin/python
from __future__ import print_function  #allows print as function
import sys
import csv # see https://docs.python.org/2/library/csv.html

#download the responses to this file
FN = 'q2.csv'
GRADE_FILE_HEADER = """*/,
* this file generated by quiz marking python script
q2 / 6
"""

# ouch, had to hack out , in correct answer by hand.
answer = [
    "TRUE",
    "The rules will be philosophically consistent given they are derived from the same ethical model",
    "balance the overall benefit vs harm of the alternatives so as to choose the best one.",
    "That effect all people now and in the future",
    "All possible options",
    "FALSE"
]

# be paranoid about data until sure it's clean
SCRUB = False

#print question stats
PRINT_STATS = True

# just give mark of 1 or zero
PASS_OR_FAIL = False

# make this into python module
execfile("mark-quiz.py")
