#!/usr/bin/python
from __future__ import print_function  #allows print as function
import sys
import csv # see https://docs.python.org/2/library/csv.html

#download the responses to this file
FN = 'q5.csv'
GRADE_FILE_HEADER = """*/,
* this file generated by quiz marking python script
q5 / 3
"""

answer = [
"Small expert group of engineers working on source code that is private between major releases",
"A giant noisy loosely oganized throng of potentially unwashed engineers working on open software that is freely available on the internet as they work",
"When many people are trying to figure out a bug somebody is bound to have just the right context for the bug to seem obvious.",
"SKIP_ME" #"It keeps users interested as the software constantly changes"
]

# be paranoid about data until sure it's clean (missing students)
SCRUB = True

PRINT_STATS = True

# just give mark of 1 or zero
PASS_OR_FAIL = False

VERBOSE = False

# make this into python module
execfile("mark-quiz.py")
