#!/usr/bin/python
from __future__ import print_function  #allows print as function
import sys
import csv # see https://docs.python.org/2/library/csv.html

#download the responses to this file
FN = 'q3.csv'
GRADE_FILE_HEADER = """*/,
* this file generated by quiz marking python script
q3 / 4
"""

# ouch, had to hack out , in correct answer by hand.
answer = [
    "Aid to ethical decision making",
    "TRUE",
    "FALSE",
    "Ejection from ACM"
]

# be paranoid about data until sure it's clean
SCRUB = False

PRINT_STATS = True

# just give mark of 1 or zero
PASS_OR_FAIL = False

# make this into python module
execfile("mark-quiz.py")
